name: lua_ls-typecheck
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  type-check:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.2.1
        shell: devenv shell bash -- -e {0}
        with:
          configpath: ".luarc.json"
          directories: |
            lua
